feat: fixes the drupal-regex command.

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -28,9 +28,21 @@ global_files:
 
 # List of actions to run after installing the addon.
 post_install_actions:
-# - chmod +x ~/.ddev/commands/web/somecommand
-# - touch somefile.${GOOS}.${DDEV_WEBSERVER}
-# - perl -pi -e 's/oldstring/newstring/g' docker-compose.addon-template.yaml
+- |
+  #ddev-nodisplay
+  if [ -f .ddev/.env ] && ! grep '#ddev-generated' .ddev/.env; then
+    echo "Existing .ddev/.env does not have #ddev-generated, so it can't be updated"
+  exit 2
+  fi
+- |
+  cat <<-END > .ddev/.env
+  #ddev-generated
+  MSSQL_EXTERNAL_PORT=1433
+  MSSQL_SA_PASSWORD=Password12!
+  MSSQL_PID=Evaluation
+  MSSQL_DB_NAME=master
+  MSSQL_HOST=localhost
+  END
 
 # Advanced usage - yaml files can be read in and then used as go template actions
 # in pre_install_actions and post_install_actions
